### ISSUE TITLE
Multiple destinations on the same route

### ISSUE THREAD

**Issue by RudiZhang** [reddeviln/RouteChecker#1]
Hi, Thank you for the great plugin!
Is it possible to identify the destination column as multiple airports? They all start from the same airport, but the destination is different, and the route is the same in the FIR, and there is no change.
For example:
Dep: ZBAA
Arr: RJAA RJBB RJOO RJTT UHSS UHWW
All route is DOTRA B334 TGO G341 WQG B451 BISUN
If each airport is listed in a row, it will be a very large workload.

Also, Is it possible to detect that the specified route is included in the route? Under normal circumstances, the DEL of each country will only check the route within its own country, but not the destination.

Thanks!

**Comment by reddeviln** [comment]
Hello! At the moment you have to have a row for each destination airport or area. So if you provide a route with destination "E" this route will be regarded as valid for all destination icaos starting with E. Also: routechecker just tries to find the provided route somewhere in the pilot filed route. So if you just provide the FIR part it is already working fine

**Comment by RudiZhang** [comment]
If it is the same FIR but different airports, the same route? If every airport is relisted, I would have to spend a lot of time for each update. It would be better if spaces or commas could be used to distinguish multiple designated airports. :) 

Route is IDKEX B339 ASILA A575 INTIK A575 UDA R372 AMUTA/K0870F360 R229 KESUM R372 ADONI B800 KUMOD A307 MAGOM/K0847F380 A307 SOREB T631 NJC G716 KEGUL/K0828F360 A714 KOMEK/N0461F400 DCT XIDMI DCT ZOL P600 KLONN UP600 TRN DCT BLACA DCT NELBO DCT NIMAT

and route in csv is IDKEX B339 ASILA A575 INTIK, that is the part of the route, but it still shows "X"

**Comment by reddeviln** [comment]
I see that is a valid feature request to have multiple airports in destination. Assign a mouse click to the "get routes" function provided by the plugin that will give you the output of all valid routes the plugin will accept. Compare that to the filed routing. The plugin can handle DCT and splitted airways

**Comment by RudiZhang** [comment]
Ah I see!!!! thank you!

**Comment by reddeviln** [comment]
Feature is available (use : to specify different destinations "VHHH:VHHX,...") at the ARBControllerpack repository now. This repository will not be worked on.
