### ISSUE TITLE
Enable for FL restrictions for certain FLs only

### ISSUE THREAD

**Issue by amosngSP** [reddeviln/RouteChecker#4]
Hello,

In the South East Asia Region, we have a Flight Level Allocation Scheme, which means certain airways you can fly only on certain FLs.

An example as below:

![image](https://user-images.githubusercontent.com/40349656/118403930-65df7580-b6a3-11eb-8a0d-76cfa05368ae.png)

As some of these FLs do not follow the east/west convention, it'll be great if this can be ignored out entirely, and to take the FLAS input instead.

**Comment by reddeviln** [comment]
I will look into it. "Lower than" flight level restrictions are working already.
