### ISSUE TITLE
Add a remarks section for the RouteChecker

### ISSUE THREAD

**Issue by amosngSP** [reddeviln/RouteChecker#5]
Hello Nils,

Many thanks for your assistance with this plugin.
As a airspace I am helping out with is undergoing a major airspace change, and that there may be multiple routes based on old and new AIRAC, is it possible to add a remarks column for the csv file so that when controller click on the RouteValidator, it shows the different routings, and the reason for each routing?

**Comment by reddeviln** [comment]
That is doable.
