### ISSUE TITLE
RouteChecker crash

### ISSUE THREAD

**Issue by amosngSP** [reddeviln/RouteChecker#6]
Hi, during my controlling session, RouteChecker crashed.
![image](https://user-images.githubusercontent.com/40349656/136658510-9743ce21-0898-4721-a8d2-456272927a04.png)
After this RouteChecker automatically unloads itself from Euroscope

**Comment by amosngSP** [comment]
To addon, when trying to reload, I realised it crashed at a particular flightplan:
![image](https://user-images.githubusercontent.com/40349656/136658588-b5a637ed-dfee-467d-923b-9dd75d25849b.png)
This is what I currently have in the csv file. 
![image](https://user-images.githubusercontent.com/40349656/136658599-0a84b0fd-7ffb-42a0-a74d-f474ee9872e8.png)
Removing ">270" and loading the plugin back causes no issue. Is there a way to set a minimum flight level?

**Comment by reddeviln** [comment]
Currently there is no ability to set a minimum level. I will add that though.

**Comment by reddeviln** [comment]
Feature is available at the ARBControllerpack repository now. This repository will not be worked on.
